#!/bin/bash

for file in *; 
do

    if [ -d "$file" ]; 
    then
        archiveAndDelete "$file" "$file"
        7z a -tzip -sdel "$file.cbz" "$file";
    else
        ext="${file##*.}";
        basename="${file%.*}";

        if [ $ext = "rar" ]; then
            dirname="temp_$basename";
            7z x "$file" -O"$dirname";
            archiveAndDelete "$basename" "$dirname"
            7z a -tzip -sdel "$basename.cbz" "$dirname";
        fi
        
        if [ $ext = "zip" ]; then
            basename="${file%.*}";
            mv "$file" "$basename.cbz";
        fi
    fi
done